export const START_GET_BOOKS = "START_GET_BOOKS";
export const COMPLETE_GET_BOOKS = "COMPLETE_GET_BOOKS";
export const ERROR_GET_BOOKS = "ERROR_GET_BOOKS";

export const START_CREATE_BOOK = "START_CREATE_BOOK";
export const COMPLETE_CREATE_BOOK = "COMPLETE_CREATE_BOOK";
export const ERROR_CREATE_BOOK = "ERROR_CREATE_BOOK";

export const START_BORROW_BOOK = "START_BORROW_BOOK";
export const COMPLETE_BORROW_BOOK = "COMPLETE_BORROW_BOOK";
export const ERROR_BORROW_BOOK = "ERROR_BORROW_BOOK";