export const START_CREATE_USER = "START_CREATE_USER";
export const COMPLETE_CREATE_USER = "COMPLETE_CREATE_USER";
export const ERROR_CREATE_USER = "ERROR_CREATE_USER";

export const START_GET_USERS = "START_GET_USERS";
export const COMPLETE_GET_USERS = "COMPLETE_GET_USERS";
export const ERROR_GET_USERS = "ERROR_GET_USERS";